[package]
name = "compare-onnx-runtimes"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
candle-core = "0.7.2"
candle-onnx = "0.7.2"
ndarray = "0.16.1"
ort = "2.0.0-rc.6"
tokio = { version = "1.40.0", features = ["full"] }
tract-onnx = "0.21.7"
wonnx = "0.5.1"
